import { UniversityConfig, ThemePreset } from '../types';

export const defaultUniversityConfig: UniversityConfig = {
  name: 'Edunexa',
  shortName: 'Edunexa',
  motto: 'Sapientia, Innovatio et Virtus',
  mottoTranslation: 'Wisdom, Innovation, and Leadership',
  established: 2001,
  location: 'North Hill Campus & Tech Innovation District, Boston, MA',
  campusSize: '120 Acres Waterfront & Smart Learning Campus',
  studentCount: 2500,
  facultyCount: 150,
  acceptanceRate: '14.2%',
  employmentRate: '98.4%',
  endowment: '$42.5 Million',
  researchFunding: '$18.5 Million / year',
  address: {
    street: '100 Academy Boulevard',
    city: 'Boston',
    state: 'MA',
    zip: '02115',
    country: 'United States',
  },
  contact: {
    admissionsPhone: '+1 (617) 555-0120',
    admissionsEmail: 'admissions@edunexa.edu',
    generalPhone: '+1 (617) 555-0100',
    generalEmail: 'info@edunexa.edu',
    emergencyHotline: '+1 (617) 555-9900',
  },
  socials: {
    twitter: 'https://twitter.com/edunexa_edu',
    linkedin: 'https://linkedin.com/school/edunexa',
    instagram: 'https://instagram.com/edunexa_official',
    facebook: 'https://facebook.com/edunexa.edu',
    youtube: 'https://youtube.com/edunexa',
  },
  accreditations: [
    'International Baccalaureate (IB) World School',
    'New England Association of Schools and Colleges (NEASC)',
    'Cognia Global Accreditation',
    'National Association of Independent Schools (NAIS)',
  ],
};

export const themePresets: ThemePreset[] = [
  {
    id: 'oxford-navy',
    name: 'Academic Sapphire & Royal Gold',
    subtitle: 'Classic Heritage & Sovereign Scholarly Tradition',
    primary: '#091e3a',
    primaryHover: '#051224',
    secondary: '#133563',
    accent: '#d97706',
    accentHover: '#b45309',
    gold: '#f59e0b',
    surface: '#f8fafc',
    badge: '#091e3a',
    fontHeading: 'font-serif',
  },
  {
    id: 'cambridge-crimson',
    name: 'Crimson Heritage & Warm Gold',
    subtitle: 'Distinguished Ivy & Classical Academy Aesthetic',
    primary: '#5c0d1b',
    primaryHover: '#440913',
    secondary: '#7c1628',
    accent: '#d4af37',
    accentHover: '#b89628',
    gold: '#e6c34f',
    surface: '#faf7f7',
    badge: '#5c0d1b',
    fontHeading: 'font-serif',
  },
  {
    id: 'ivy-green',
    name: 'Emerald Forest & Bronze',
    subtitle: 'Sustainability, Environmental Science & Life Labs',
    primary: '#063826',
    primaryHover: '#032317',
    secondary: '#0c4d36',
    accent: '#d97706',
    accentHover: '#b45309',
    gold: '#eab308',
    surface: '#f6faf7',
    badge: '#063826',
    fontHeading: 'font-serif',
  },
  {
    id: 'polytechnic-slate',
    name: 'Deep Obsidian & Cyan Frontier',
    subtitle: 'Advanced STEM, Robotics & Quantum Innovation',
    primary: '#090d16',
    primaryHover: '#030509',
    secondary: '#131b2e',
    accent: '#0284c7',
    accentHover: '#0369a1',
    gold: '#38bdf8',
    surface: '#f8fafc',
    badge: '#090d16',
    fontHeading: 'font-sans',
  },
];
