version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: aura-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: shopsphere_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ../database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

  redis:
    image: redis:7-alpine
    container_name: aura-redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: aura-backend-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=shopsphere_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=supersecretjwtkeyforauraenterpriseplatform2026
      - JWT_REFRESH_SECRET=supersecretjwtrefreshkeyforauraenterpriseplatform2026
      - JWT_ACCESS_EXPIRY=15m
      - JWT_REFRESH_EXPIRY=7d
      - RAZORPAY_KEY_ID=rzp_test_placeholderkey
      - RAZORPAY_KEY_SECRET=placeholderkeysecret
      - RAZORPAY_WEBHOOK_SECRET=webhooksecret
    depends_on:
      - db
      - redis

  customer-portal:
    build:
      context: ../customer-portal
      dockerfile: Dockerfile
    container_name: aura-customer-portal
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  admin-portal:
    build:
      context: ../admin-portal
      dockerfile: Dockerfile
    container_name: aura-admin-portal
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  mysql-data:
  redis-data:
